spring:
  datasource:
    username: sa
    url: jdbc:h2:tcp://localhost/~/musinsa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.musinsa.shop: debug
    org.hibernate:
      SQL: debug
      # type.descriptor.sql: trace
    org.springframework.web: debug